version: 2
jobs:
  build:
    working_directory: ~/example-maven-circleci
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:

      - checkout

      - restore_cache:
          key: example-maven-circleci-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: example-maven-circleci-{{ checksum "pom.xml" }}
      
      - run: mvn -Dtest=Example test
      
      - store_test_results:
          path: target/surefire-reports      
